### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by krizzzly** [solspace/craft3-freeform#164] opened 2021-06-18 11:49 UTC
**Describe the bug or issue you're experiencing**
Searching for any submissions with a query is resulting in an error. The ajax error result: `Unknown column 'k4_freeform_submissions.field_88' in 'where clause'`

i checked the SQL query and it seems that freeform now searchs in every field.

![Bildschirmfoto 2021-06-18 um 13 46 54](https://user-images.githubusercontent.com/48832704/122556380-b6981480-d03b-11eb-967c-399e07352efb.png)

But some of the fields dont exist anymore resulting in an error

**Expected behavior**

should find submissions.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.6.15
- Freeform Version: 3.11.6
- Freeform Edition: PRO
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment] 2021-06-18 18:45
Thanks @krizzzly. We'll get a fix out for this early next week. :)

**Comment by cruiser12** [comment] 2021-06-20 14:16
Regarding the performance of the new search, maybe we can have a lightswitch setting for that, because we have integrated some key important data like name and email into the title, so we are good with the search so far and it was quite fast. Thx for considering that. Kind regards

**Comment by gustavs-gutmanis** [comment] 2021-06-21 08:11
This issue has been resolved and will be released in the upcoming version.

**Comment by krizzzly** [comment] 2021-06-22 15:44
i updated the plugin to version 3.11.7. Unfortunately the error keeps the same. `Unknown column 'k4_freeform_submissions.field_88' in 'where clause'`

I also now checked the db table `k4_freeform_submissions` and there is a field with name `field_88`.
Also 'k4_freeform_fields' has an line with id `88`.
There is something with that query in general, because `freeform_submissions.field_88` is the first field listed in `SELECT` part of the query.
Removing all the fields from `SELECT` and `WHERE` it will search in title only and it works well.

**Possible Solution:**
In subquery you have a `WHERE` part that uses column names including DB prefixes, but the JOIN is already adding aliases to get rid of the DB prefix.

Here is the related sql query.

![Bildschirmfoto 2021-06-22 um 17 24 29](https://user-images.githubusercontent.com/48832704/122953431-00a43180-d37f-11eb-9ec4-bc7eedeee19d.png)

**Comment by krizzzly** [comment] 2021-06-22 15:53
i can confirm now that the suggested solution works well.

![Bildschirmfoto 2021-06-22 um 17 52 41](https://user-images.githubusercontent.com/48832704/122957945-b45af080-d382-11eb-9f68-bd3d23a2b9e7.png)

**Comment by gustavs-gutmanis** [comment] 2021-06-23 08:25
@krizzzly could you try out the `dev-master` and see if the issue is fixed now?

**Comment by krizzzly** [comment] 2021-06-23 09:15
@gustavs-gutmanis i updated to `dev-master` and it works well. 👍🏻

**Comment by gustavs-gutmanis** [comment] 2021-06-23 09:20
Glad to hear! I'm going to close this ticket then.

**Closed by gustavs-gutmanis** 2021-06-23 09:20 UTC
Labels: issue
