### ISSUE TITLE
Can't use more than one Email Marketing field in one form

### ISSUE THREAD

**Issue by jawadharaba98** [solspace/craft3-freeform#899] opened 2023-10-27 08:47 UTC
**Describe the bug or issue you're experiencing**

I am using Campaign Monitor field in freeform and it is working as expected when i use only one but when i am trying to use more than one the GraphQL mutation query only include the handle of one of them and that is causing an error when trying to submit "Unknown argument "YaGkrAVQj" on field "save_feedback_Submission" of type "Mutation".
I also checked the GraphQL mutation query in the explorer and it only has one handle.

**Steps to reproduce**

1.Make a new form and add 2 Campaign monitors fields to it.
2.Map each one to Mail list.

**Expected behavior**

GraphQL mutation query that includes both handles.
Campaign monitor field 1 handle  : YaGkrAVQj
Campaign monitor field 2 handle  : r2J9j2qRp

As u can see in the image the query only includes one argument for field 2 and not for field 1
![image](https://github.com/solspace/craft-freeform/assets/57747646/d131598c-ce51-4ef7-a301-929b132f74e8)

**Craft & Plugin Info (please complete the following information):**

- Craft Version : 4.5.9
- Freeform Version : 4.1.10
- Freeform Edition: Pro
- Fresh Install 

**Additional context**

Element API | 3.0.1.1
Headless Craft with react.
Using GraphQL for submit.

**Comment by mazaalai** [comment] 2023-10-30 14:26
I'm having the same issue. is this working as intended or am i doing something wrong ?

**Comment by kjmartens** [comment] 2023-10-30 19:43
Hi @jawadharaba98 and @mazaalai,

Sorry for the trouble you're experiencing. I will check with a developer to see if this is a limitation or something we can quickly adjust. 🙂

**Comment by kjmartens** [comment] 2023-11-09 21:05
This has been addressed in Freeform 4.1.12+ @jawadharaba98 and @mazaalai. 🙂 

You can check out the updated docs here:
https://docs.solspace.com/craft/freeform/v4/headless/graphql/

**Closed as completed by kjmartens** 2023-11-09 21:05 UTC
Labels: issue
