### ISSUE TITLE
/cpresources/freeform-scripts-front-end-captchas-recaptcha/v3.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by atelierbim** [solspace/craft3-freeform#1232] opened 2024-04-24 08:36 UTC
**Describe the bug or issue you're experiencing**
Front end form protected by reCaptcha keep displaying an error message to the visitors: 
Please verify that you are not a robot.

in the console: /cpresources/freeform-scripts-front-end-captchas-recaptcha/v3.js net::ERR_ABORTED 404 (Not Found)

**Steps to reproduce**

1.
2.

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4 latest
- Freeform Version: 5 latest
- Freeform Edition: PRO
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment] 2024-04-25 01:31
Hi @atelierbim,

I wonder if this is a similar issue as described here:
https://docs.solspace.com/craft/freeform/v5/common-issues/#_404-errors-for-freeform-plugin-js

Can you try switching the **Freeform Script Insert Type** setting (Craft CP → Freeform → Settings → Form Behavior) to **As Files** instead and see if that resolves it? 🙂

**Comment by atelierbim** [comment] 2024-04-25 05:00
Hi @kjmartens,
I did try this. It does not work. It seems that it is related to my hosting on Craft Cloud. Here's the console output for the files:

`GET https://cdn.craft.cloud/7b8beba8-e101-4748-bea8-5b552bef2af7/builds/9be3a0f5-21da-41a4-8773-aa286088b974/cpresources/freeform-styles-front-end-plugin/freeform.css net::ERR_ABORTED 404 (Not Found)`

`GET https://cdn.craft.cloud/7b8beba8-e101-4748-bea8-5b552bef2af7/builds/9be3a0f5-21da-41a4-8773-aa286088b974/cpresources/freeform-scripts-front-end-plugin/freeform.js net::ERR_ABORTED 404 (Not Found)`

`GET https://cdn.craft.cloud/7b8beba8-e101-4748-bea8-5b552bef2af7/builds/9be3a0f5-21da-41a4-8773-aa286088b974/cpresources/freeform-scripts-front-end-captchas-recaptcha/v3.js net::ERR_ABORTED 404 (Not Found)`

Pretty annoying it's happening on the live site...

**Comment by atelierbim** [comment] 2024-04-30 06:29
Hi, is there any update on this?

**Comment by kjmartens** [comment] 2024-04-30 23:21
Sorry for the delay @atelierbim,

I can't reproduce this issue happening on my test site, and I haven't heard of anyone reporting this issue yet.

Can you confirm the exact versions of Freeform and Craft you're using? If not the latest available, please try updating.

I guess switch it back to **Encrypted Payload**. Can you screenshot me what your reCAPTCHA settings look like in the form builder for the affected form? 🙂 

Further to this... we recommend not using the **Display Error** behavior for reCAPTCHA v3 since the user cannot make any changes on their side of things. Instead, you should use **Send to Spam Folder**. It would also then include the score the user was given by reCAPTCHA when viewing the submission in the Spam Folder. 🙂 

<img width="806" alt="Screenshot 2024-04-30 at 6 16 52 PM" src="https://github.com/solspace/craft-freeform/assets/1821674/6d01d24f-5ded-4317-808b-8e1b1c48d422">

**Comment by kjmartens** [comment] 2024-05-22 04:29
Hi @atelierbim,

I just wanted to let you know that we're working on a fix for a potential issue with support for Craft Cloud. 🙂

**Comment by kjmartens** [comment] 2024-05-24 17:02
This should now be resolved in Freeform 5.3.0+ 🙂

**Closed as completed by kjmartens** 2024-05-24 17:02 UTC
Labels: issue
