### ISSUE TITLE
Textarea quotation marks prevent submission

### ISSUE THREAD

**Issue by TUSAB-web** [solspace/craft3-freeform#187] opened 2021-08-09 19:58 UTC
**Describe the bug or issue you're experiencing**
When entering quotation marks (cut-and-pasted from another application) in a textarea field, the submit button doesn’t function, so the user cannot submit. Removing the quotes allows the person to submit. Typing quotes directly into the field seems to work fine, so I believe it is those “curly quotes” inserted by a program like MS Word they cut/pasted from, and they are the issue.

**Steps to reproduce**

1. Enter text with quotation marks in it (double quotes like “these ones")
2. Press submit
3. Nothing happens

**Expected behavior**

Form should submit

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.4
- Freeform Version: 3.11.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: upgrade?

**Additional context**

I saw item #73 seemed to be a similar issue but with different characters.

**Comment by kjmartens** [comment] 2021-08-09 22:19
I can't personally duplicate this issue. Are you able to install the [demo templates](https://docs.solspace.com/craft/freeform/v3/setup/demo-templates.html) included with Freeform, visit the Bootstrap section, and try submitting the form there with these special characters and see if the issue persists? :)

**Comment by TUSAB-web** [comment] 2021-08-10 20:02
Our site is usarmyband dot com - we have a “feedback” link at the top of the page. The form submits with the “weird” characters when run in our local environment, but not on the server.

**Comment by kjmartens** [comment] 2021-08-10 20:04
Thanks for the additional information, but I still would need you to confirm my previous question about testing the form in the isolated demo templates area. 🙂

**Comment by TUSAB-web** [comment] 2021-08-10 20:10
Thank you - I installed the demo templates on the staging server (the same problem happens on staging as it does on live). The bootstrap demo works. I looked at the form in question and it is set with a formatting templates of “Flexbox” not bootstrap.

**Comment by kjmartens** [comment] 2021-08-11 20:48
What I believe might more likely be the issue is your server environment and/or page template/layout. The demo templates offer an isolated area to test your forms, free of other global CSS/JS and other elements in the page (compared to a real-world template/page). Additionally, the Bootstrap section in the demo templates specifically overrides any formatting template for the form too, so if there was an error in your formatting template (if you're using a custom one) it could be ruled out as well. In this case, it sounds like you're using the built-in Flexbox formatting template that comes with Freeform, and the demo area works, so I would suspect that the issue could have something to do with your page template/layout.

You might want to play around with this a bit (perhaps starting out with something basic in a template and then adding more and more real-world additional code and elements from the page into it and see if/when it begins to break. :)

**Comment by TUSAB-web** [comment] 2021-08-12 21:51
Kelsey,

Thank you very much. I seem to have found the issue. Since it’s only happening on our live site, not on staging or local, it is related to the Web Application Firewall our site lives behind. I used our internal systems to hit the live site without going through the WAF and the form submitted normally. I will talk to the administrators of the WAF about this problem. Thanks for the great info that helped me troubleshoot this.

**Comment by kjmartens** [comment] 2021-08-12 22:25
Thanks, I will close the issue now. 🙂

**Closed by kjmartens** 2021-08-12 22:25 UTC
Labels: issue
