### ISSUE TITLE
AJAX forms duplicating form

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#1064] opened 2024-02-19 15:44 UTC
**Describe the bug or issue you're experiencing**
We have a data protection statement at the bottom of our forms.
On page 1 it shows fine. But on other pages it is duplicating,

**Steps to reproduce**

1. Editted template to include DP statment
2. Gone to page 2 on AJAX form and the statement is there twice.

```
{# Display form field rows and columns #}
{{ rowMacro.render(form.rows, form) }}

{# Render the closing form tag #}
{{ form.renderClosingTag }}

<div class="flex flex-wrap -mx-3{{ form.customAttributes.rowClass }}">
	<div class="main-column-class w-full px-3 mb-6 md:w-full lg:w-full xl:w-full text-sm">
		{{ siteWide.dataProtectionStatement }}
	</div>
</div>
```

**Expected behavior**

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 
- Freeform Version:
- Freeform Edition:
- Fresh Install or Upgrade:

**Additional context**

**Comment by kjmartens** [comment] 2024-02-22 18:54
I'm assuming this is a duplicate of this: https://github.com/solspace/craft-freeform/discussions/1088

**Closed as completed by kjmartens** 2024-02-22 18:54 UTC
Labels: duplicate
